name: MetaMask Release Test

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR base branch and comment
        if: |
          github.event.issue.pull_request &&
          github.event.comment.body == 'RELEASE APPROVED' &&
          github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'COLLABORATOR'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_url="${{ github.event.issue.pull_request.url }}"
          base_branch=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$pr_url" | jq -r .base.ref)
          if [[ $base_branch == release/* ]]; then
            echo "PR targets release/* branch. Proceeding."
          else
            echo "PR does not target release/* branch. Exiting."
            exit 1
          fi
      - uses: actions/checkout@v4
        if: success() # Only runs if previous step succeeded